# require: rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/**"
    - "db/schema.rb"
    - "db/migrate/**"
    - "examples/**"

# BEGIN
Style/Documentation:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
# END
