AllCops:
  SuggestExtensions: false
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'
    - 'examples/**/*'
    - 'db/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
